### ISSUE TITLE
Implement a pass to identify number of callers (callsites) of a function (or instruction in a function)

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#23]
We need this to either avoid inserting asserts in functions with more than one call site (see #19), or to insert asserts with multiple number of correct hashes (i.e. the number of the callsites)

**Comment by anahitH** [comment]
Implemented a pass to collect number of call sites for each input independent function. Pass does not collect this information for functions called from loops. Input dependent functions are also skipped. First it is not possible to statically identify how many times input dependent function will be called at run time. Besides, given that the results of this pass are going to be used in OH and OH skips input dependent functions, there is no need to have call site information for input dependent functions.

The pass additionally collects functions that are called in a loop. If a function is called from a loop, then all functions called in that function are also going to be marked as called from a loop. 

Pass can be invoked by "-callsite-info" argument.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Thursday Jan 04, 2018 at 23:19 GMT_

----

Implemented a pass to collect number of call sites for each input independent function. Pass does not collect this information for functions called from loops. Input dependent functions are also skipped. First it is not possible to statically identify how many times input dependent function will be called at run time. Besides, given that the results of this pass are going to be used in OH and OH skips input dependent functions, there is no need to have call site information for input dependent functions.

The pass additionally collects functions that are called in a loop. If a function is called from a loop, then all functions called in that function are also going to be marked as called from a loop. 

Pass can be invoked by "-callsite-info" argument.
