### ISSUE TITLE
For the time being make sure asserts won't be injected in functions with multiple callsites

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#24]
This is a quick fix (hack) can be disable when #22 is implemented
Use #23 to detect number of callsites, what about indirect calls? @anahitH

**Comment by anahitH** [comment]
Indirect calls are handled in FunctionCallSiteInformationPass. It uses IndirectCallSitesAnalysis from input dependency analyzer project to find all potential targets for an indirect call site. Then it increments call site numbers of all targets.

**Comment by mr-ma** [comment]
Perfect!

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Friday Jan 05, 2018 at 19:46 GMT_

----

Indirect calls are handled in FunctionCallSiteInformationPass. It uses IndirectCallSitesAnalysis from input dependency analyzer project to find all potential targets for an indirect call site. Then it increments call site numbers of all targets.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Tuesday Jan 09, 2018 at 17:16 GMT_

----

Perfect!
