### ISSUE TITLE
What's the intuition behind ObliviousHashInsertionPass::insertLogger decisions

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#25]
@anahitH Do you remember why do we care about the type of the instruction before/after which we insert an assert call?

**Comment by anahitH** [comment]
Normally assertions are inserted randomly. For each instruction, which we can consider to be “insertion point”, we randomly decide to add assertion at that point or not.
However for Cmp instructions and Call instructions we always add assertions. We thought it will provide more security to have assertion before instructions that translate to jumps. But this was just an assumption. For cmp instructions we even make sure that the hash variable containing hash of that cmp instruction is checked in the assert inserted, while for the other asserts hash variables to be checked are chosen randomly.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Tuesday Jan 09, 2018 at 21:21 GMT_

----

Normally assertions are inserted randomly. For each instruction, which we can consider to be “insertion point”, we randomly decide to add assertion at that point or not.
However for Cmp instructions and Call instructions we always add assertions. We thought it will provide more security to have assertion before instructions that translate to jumps. But this was just an assumption. For cmp instructions we even make sure that the hash variable containing hash of that cmp instruction is checked in the assert inserted, while for the other asserts hash variables to be checked are chosen randomly.
