### ISSUE TITLE
Investigate further instructions for hashing

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#28]
Getelement is one candidate for hashing arrays...

**Comment by anahitH** [comment]
Another candidate is invoke instruction, which should be processed the same way Call instruction is

**Comment by anahitH** [comment]
Implemented hashing of GetElementPtr instruction. 
GetElementPtr instruction is used to access elements of arrays and fields of structs and classed.
Value of GetElementPtr is hashed in case if it's integer. Input dependent indices of the instruction are also hashed.

E.g. for the following GetElementPtr instruction arrayidx will be hashed if second (index 1) element of array is input dependent. Indices 0 and 1 will be hashed always.

_%arrayidx = getelementptr inbounds [7 x i32], [7 x i32]* %array, i64 0, i64 1_

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday Jan 17, 2018 at 20:49 GMT_

----

Another candidate is invoke instruction, which should be processed the same way Call instruction is

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Thursday Jan 18, 2018 at 00:16 GMT_

----

Implemented hashing of GetElementPtr instruction. 
GetElementPtr instruction is used to access elements of arrays and fields of structs and classed.
Value of GetElementPtr is hashed in case if it's integer. Input dependent indices of the instruction are also hashed.

E.g. for the following GetElementPtr instruction arrayidx will be hashed if second (index 1) element of array is input dependent. Indices 0 and 1 will be hashed always.

_%arrayidx = getelementptr inbounds [7 x i32], [7 x i32]* %array, i64 0, i64 1_
