### ISSUE TITLE
hashUpdated for module instead of function

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#34]
Currenty OH keeps _hashUpdated_ for each function, i.e. before starting processing of a function _hashUpdated_ is initialized with false.
Now consider following situation: in function _foo_ we have inserted hashes but no assertion. This means  at the end of processing function _foo_ we'll have _hashUpdated_ true. Now when starting processing of function _boo_, _hashUpdated_ will be reset to false, and even if we have valid location to insert assert, it won't be inserted because _hashUpdated_ is false.
Having _hashUpdated_ for module scope seems to solve this problem.

**Comment by mr-ma** [comment]
@anahitH  Fair, please feel free to update the scope.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Monday Feb 05, 2018 at 14:02 GMT_

----

@anahitH  Fair, please feel free to update the scope.
