### ISSUE TITLE
Compute expected hash values for short range hashes

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#40]
Implement expected hash computation for short range hashes

**Comment by anahitH** [comment]
Try slicing for precomputation (dg)

**Comment by anahitH** [comment]
commit 851bf5c759f71443328671c1109c62f7563520b3 is the initial commit for short-range hash pre-computation for a simplified programs (no loops for now).

Along with inserting OH instructions, bitcode is transformed to make sure all paths are executed. This is done by copying each short OH path into a separate function, for which a call site is inserted in a deterministic location. When running the resulted binary all hashes should be computed.

Note that the patcher needs to be modified to patch multiple values for each placeholder, as those are not anymore unique. I.e. a copy of a path contains the same placeholders as the original path.

**Comment by anahitH** [comment]
Add post patching pass to remove all the redundant call sites and functions added for pre-computation. 
Binary after post patching should have the same semantics as the binary before applying OH plus OH functionality

**Comment by anahitH** [comment]
Modify short range OH computation with the following steps:

- For each oh path insert an assertion at the end of the path, i.e. in the last BB of the path
- Slice w.r.t. each short range assertion using dg. 
- Refine the slice from the previous step by removing data dependent instructions 
- Extract refined slice into a new function
- Insert call to the extracted function in main

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday Mar 07, 2018 at 13:04 GMT_

----

Try slicing for precomputation (dg)

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Sunday Mar 11, 2018 at 16:24 GMT_

----

commit 851bf5c759f71443328671c1109c62f7563520b3 is the initial commit for short-range hash pre-computation for a simplified programs (no loops for now).

Along with inserting OH instructions, bitcode is transformed to make sure all paths are executed. This is done by copying each short OH path into a separate function, for which a call site is inserted in a deterministic location. When running the resulted binary all hashes should be computed.

Note that the patcher needs to be modified to patch multiple values for each placeholder, as those are not anymore unique. I.e. a copy of a path contains the same placeholders as the original path.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Sunday Mar 11, 2018 at 16:26 GMT_

----

Add post patching pass to remove all the redundant call sites and functions added for pre-computation. 
Binary after post patching should have the same semantics as the binary before applying OH plus OH functionality. Post patching should be done on a binary

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Tuesday Mar 27, 2018 at 06:36 GMT_

----

Modify short range OH computation with the following steps:

- For each oh path insert an assertion at the end of the path, i.e. in the last BB of the path
- Slice w.r.t. each short range assertion using dg. 
- Refine the slice 
             - Remove instructions that are not in the path which is being processed.
             - Remove data dependent instructions 
- Extract refined slice into a new function
- Insert call to the extracted function in main
