### ISSUE TITLE
Insert a single assertion for each OH path

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#44]
As described in issue #40 a single assertion needs to be inserted for each oh path. The assertion has to be inserted in the last BB of the given path and there shouldn't be any hashing after it.
To facilitate next step of short-range hash computation i.e. slicing (see issue #40 ) use unique function names for each assertion.

**Comment by anahitH** [comment]
Modified short range hashing to have a single assertion for each oh path. Path assertion is inserted at the end of path, i.e. before terminating instruction of the last block of the path. Assertion has a unique name for short range hashes. The name is constructed from function name and path number, e.g. assert_test_path_0, will be assertion for the first path in function test. This will guarantee that all path assertions have unique names. For global hashes and assertions everything works as before.
Note that after these modifications patcher won't work. Also it is not possible to generate an executable, as definitions for short range assertions are not present.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday Mar 28, 2018 at 10:43 GMT_

----

Modified short range hashing to have a single assertion for each oh path. Path assertion is inserted at the end of path, i.e. before terminating instruction of the last block of the path. Assertion has a unique name for short range hashes. The name is constructed from function name and path number, e.g. assert_test_path_0, will be assertion for the first path in function test. This will guarantee that all path assertions have unique names. For global hashes and assertions everything works as before.
Note that after these modifications patcher won't work. Also it is not possible to generate an executable, as definitions for short range assertions are not present.
