### ISSUE TITLE
Integrate dg with OH tool

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#45]
Integrate dg with OH to implement second step of short range oh computation described in issue #40 . 
The final goal is to get dg slice in OH as a set of instructions. This step shouldn't modify a module under analysis in any way.

**Comment by mr-ma** [comment]
@anahitH I've put a toy example together to play with dg slicer, which mimics the behaviour of our hashes. However, dg throws error as soon as it sees pointer variables :( 
See the issue that I opened some time ago
https://github.com/mchalupa/dg/issues/191

**Comment by anahitH** [comment]
Implemented first steps of dg and oh integaration in 87c9e0afdd667bca75df81076df685800d94aefc.
Made some modifications in dg CMakefiles in order to be able to compile Oh with dg. 
Current implementation fails to run due to link time errors which need further investigation.

**Comment by anahitH** [comment]
Fixed runtime error of oh with dg.
Modified usage of dg slicer in oh. Dg has checks which do not allow to build dependence graph for the same module more than once. This leaves no other way but to make all oh modifications, i.e. inserting hashes and assertions, then build dependence graph and slice w.r.t all assertions.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Tuesday Mar 27, 2018 at 08:31 GMT_

----

@anahitH I've put a toy example together to play with dg slicer, which mimics the behaviour of our hashes. However, dg throws error as soon as it sees pointer variables :( 
See the issue that I opened some time ago
https://github.com/mchalupa/dg/issues/191

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Tuesday Apr 03, 2018 at 08:12 GMT_

----

Implemented first steps of dg and oh integaration in 87c9e0afdd667bca75df81076df685800d94aefc.
Made some modifications in dg CMakefiles in order to be able to compile Oh with dg. 
Current implementation fails to run due to link time errors which need further investigation.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday Apr 11, 2018 at 21:10 GMT_

----

Fixed runtime error of oh with dg.
Modified usage of dg slicer in oh. Dg has checks which do not allow to build dependence graph for the same module more than once. This leaves no other way but to make all oh modifications, i.e. inserting hashes and assertions, then build dependence graph and slice w.r.t all assertions.
