### ISSUE TITLE
Extract oh path functions

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#47]
Extract refined sliced from issue #45,  #46 and #50 into a separate function. Extracted function should have empty argument list and void as return type. Insert call to the extracted function in main.
This is 4th and 5th steps of issue #40

**Comment by anahitH** [comment]
Skip extracting functions that will require to have arguments. It is problematic to determine call sites for those functions, without breaking SC.
This kind of functions can be generated when applying short range hashing on input dependent blocks of input independent functions, where a data independent argument is used inside the block.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday Apr 11, 2018 at 19:38 GMT_

----

Skip extracting functions that will require to have arguments. It is problematic to determine call sites for those functions, without breaking SC.
This kind of functions can be generated when applying short range hashing on input dependent blocks of input independent functions, where a data independent argument is used inside the block.

Opened an enhancement for this feature - #49
