### ISSUE TITLE
Add a section in oh statistics for number of loops, percentage of input dep arguments and hashable instructions

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#58]
Add a section in oh statistics for number of loops, percentage of input dep arguments and hashable instructions

**Comment by anahitH** [comment]
Add following data in oh stats
    - information about non-hashable instructions, i.e. number of data independent instructions which are not hashed by oh.
   - information about sensitive path coverage - number of sensitive paths and number of protected paths
   - information about function coverage - number of sensitive functions and number of protected functions.

**Comment by mr-ma** [comment]
Report the exact numbers instead of statistics

**Comment by anahitH** [comment]
Add following sections to oh statistics:

For unprotected blocks:
     -  Blocks that do not have any hashable instructions
     -  Blocks that are in data dependent loop
     -  Blocks that are in data independent loop

For unprotected instructions:
      - Non hashable instructions
      - Instructions in data dependent loop

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Tuesday Apr 24, 2018 at 11:01 GMT_

----

Add following data in oh stats
    - information about non-hashable instructions, i.e. number of data independent instructions which are not hashed by oh.
   - information about sensitive path coverage - number of sensitive paths and number of protected paths
   - information about function coverage - number of sensitive functions and number of protected functions.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Thursday Apr 26, 2018 at 09:30 GMT_

----

Report the exact numbers instead of statistics

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Friday Apr 27, 2018 at 22:20 GMT_

----

Remove numberOfSkippedArgUsingBlocks, as after implementing #66 there won't be any block skipped because of using function argument.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday May 02, 2018 at 17:32 GMT_

----

Add following sections to oh statistics:

For unprotected blocks:
     -  Blocks that do not have any hashable instructions
     -  Blocks that are in data dependent loop
     -  Blocks that are in data independent loop

For unprotected instructions:
      - Non hashable instructions
      - Instructions in data dependent loop
