### ISSUE TITLE
Apply -reg2mem pass on dataset programs before running OH

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#79]
This will allow an easy fix for issue #71

**Comment by anahitH** [comment]
A faster solution is to use MemorySSAWrapperPass analysis pass results. It's an analysis pass which can give the same information as -reg2mem, without transforming bitcode.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Monday May 21, 2018 at 21:20 GMT_

----

A faster solution is to use MemorySSAWrapperPass analysis pass results. It's an analysis pass which can give the same information as -reg2mem, without transforming bitcode.
