### ISSUE TITLE
Remove (NOP) calls in the SROH stimulation function (oh_path_functions)

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#80]
`oh_path_functions` is only used to stimulate short range functions for the GDB patcher.
NOP all the instructions in it, once GDB patcher is done.

**Comment by mr-ma** [comment]
@anahitH I was not able to fully test this as the transformed bc (with short range protection) cannot be executed anymore. I used tetris as my example. Any ideas?

**Comment by anahitH** [comment]
@mr-ma What is the reason of patched binary not running? Is it crash or something else?

I've tested your changes on testris and it works for me. oh_path_functions' content is nop-ed in the final binary and it runs without any problem.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Thursday May 24, 2018 at 16:57 GMT_

----

@anahitH I was not able to fully test this as the transformed bc (with short range protection) cannot be executed anymore. I used tetris as my example. Any ideas?

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Thursday May 24, 2018 at 17:21 GMT_

----

@mr-ma What is the reason of patched binary not running? Is it crash or something else?

I've tested your changes on testris and it works for me. oh_path_functions' content is nop-ed in the final binary and it runs without any problem.
