### ISSUE TITLE
Include branching evaluation in short range hashes 

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#82]
Hash the result of branch evaluation in SROH paths.
```
if(data_dependent){
  do stuff;
}
```
into:
```
if((t=data_dependent==true, hash1(path_variable, t), t)){
  do stuff;
}
```

**Comment by mr-ma** [comment]
Please merge

**Comment by anahitH** [comment]
Merged branch issue_82 with branch short_range_oh

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Monday May 28, 2018 at 09:16 GMT_

----

Please merge

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Monday May 28, 2018 at 10:39 GMT_

----

Merged branch issue_82 with branch short_range_oh
