### ISSUE TITLE
OH+SROH protected binary fails with incorrect hash values for program susan from mibench

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#93]
Program is in office programs group.

**Comment by anahitH** [comment]
Hashing data dep/arg dep branch instr inside a loop leads to this problem. For if-else construction the branch instr is going to be executed once in SROH path functions, while for loops it’s going to be executed more than once and the branch for if.then will always hash 1, path for if.else will hash 0, while in original function it may be 1 for one iteration and 0 for the next.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Friday Jun 08, 2018 at 19:08 GMT_

----

Hashing data dep/arg dep branch instr inside a loop leads to this problem. For if-else construction the branch instr is going to be executed once in SROH path functions, while for loops it’s going to be executed more than once and the branch for if.then will always hash 1, path for if.else will hash 0, while in original function it may be 1 for one iteration and 0 for the next.
